version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.src.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'
