version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.src.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

  celery:
    build: .
    image: web-image
    command: celery -A app.src.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mysql_db

  celery_beat:
    build: .
    image: web-image
    command: celery -A app.src.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mysql_db
