# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: TEST
#    services:
#
#      web:
#        ports:
#          - 8000:8000
#        env:
#          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
#          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#          MYSQL_USER: ${{ vars.MYSQL_USER }}
#          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
#          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
#          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
#          IEXCLOUD_API_KEY: ${{ vars.IEXCLOUD_API_KEY }}
#          CELERY_BROKER_URL: ${{ vars.CELERY_BROKER_URL }}
#          CELERY_RESULT_BACKEND: ${{ vars.CELERY_RESULT_BACKEND }}
#          REDIS_HOST: ${{ vars.REDIS_HOST }}
#
#
#      db:
#        image: mysql:8.0
#        env:
#          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
#          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#          MYSQL_USER: ${{ vars.MYSQL_USER }}
#          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
#          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
#          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
#        ports:
#          - 3306:3306

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

#      - name: Set up Python 3.10
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.10.10

      - name: Create env file
        run: |
          touch .env
          echo MYSQL_PASSWORD=${{ vars.MYSQL_PASSWORD }} >> .env
          echo MYSQL_USER=${{ vars.MYSQL_USER }} >> .env
          echo MYSQL_HOST=${{ vars.MYSQL_HOST }} >> .env
          echo MYSQL_PORT=${{ vars.MYSQL_PORT }} >> .env
          echo MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }} >> .env
          echo IEXCLOUD_API_KEY=${{ vars.IEXCLOUD_API_KEY }} >> .env
          echo CELERY_BROKER_URL=${{ vars.CELERY_BROKER_URL }} >> .env
          echo CELERY_RESULT_BACKEND=${{ vars.CELERY_RESULT_BACKEND }} >> .env
          echo REDIS_HOST=${{ vars.REDIS_HOST }} >> .env
          cat .env

      - name: Build and start Docker Compose
        run: docker-compose up --build -d

      - name: Wait for app to start
        run: |
          docker-compose exec web bash
          ls

      #Task for installing dependencies, multi-line command
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install black pytest
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi



#      - name: Migrate
#        env:
#          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
#          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#          MYSQL_USER: ${{ vars.MYSQL_USER }}
#          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
#          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
#          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
#          IEXCLOUD_API_KEY: ${{ vars.IEXCLOUD_API_KEY }}
#          CELERY_BROKER_URL: ${{ vars.CELERY_BROKER_URL }}
#          CELERY_RESULT_BACKEND: ${{ vars.CELERY_RESULT_BACKEND }}
#          REDIS_HOST: ${{ vars.REDIS_HOST }}
#        run: |
#          cd app
#          alembic upgrade head
#
#      - name: Test with pytest
#        env:
#          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
#          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
#          MYSQL_USER: ${{ vars.MYSQL_USER }}
#          MYSQL_PASSWORD: ${{ vars.MYSQL_PASSWORD }}
#          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
#          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
#          IEXCLOUD_API_KEY: ${{ vars.IEXCLOUD_API_KEY }}
#          CELERY_BROKER_URL: ${{ vars.CELERY_BROKER_URL }}
#          CELERY_RESULT_BACKEND: ${{ vars.CELERY_RESULT_BACKEND }}
#          REDIS_HOST: ${{ vars.REDIS_HOST }}
#        run: |
#          pwd
#          ls
#          pytest
